### ISSUE TITLE
Feature request: add contact profile picture to events

### ISSUE THREAD

**Issue by amitkeret** [dschuermann/birthday-adapter#86]
Hello,
I've been using your app and it's great, especially since it's the only one I found that displays contact age (even native Google calendar doesn't support this!)

Would be great if contact photos were displayed next to the events on the calendar.
Not sure if this can be done, I've seen there's an option to specify icon URLs if you're using the [calendar gadgets](https://developers.google.com/google-apps/calendar/gadgets/event/) method for creating events, not sure if it can be used in this scenario.

See the birthday event here:
![image](https://cloud.githubusercontent.com/assets/1258597/7658306/af3668ac-fb41-11e4-8f62-1d6c8bd16610.png)

Google birthdays take the picture from Google contacts, but I guess this app can use pictures stored locally in the phone contacts.
Possible?

**Comment by dschuermann** [comment]
I don't think it's possible with the public API :/ . We would need a field from http://developer.android.com/reference/android/provider/CalendarContract.EventsColumns.html that allows this.
I think Google implements this in their closed source calendar app by directly looking up pictures from G+ without using a public API that previously writes this using the content provider of Android.

**Comment by amitkeret** [comment]
What about [CUSTOM_APP_PACKAGE](http://developer.android.com/reference/android/provider/CalendarContract.EventsColumns.html#CUSTOM_APP_PACKAGE) field?
Can this be used to format a custom display for the event?

**Comment by dschuermann** [comment]
This is already utilized. It enables the button "Open in Birthday Calendar" which opens the corresponding contact. Unfortunately, the button labelcan not be changed. I don't see a way currently to add an image directly. I already use the current public API to its maximum.
